[pytest]
testpaths = tests
pythonpath = .
qt_api = pyqt5
addopts =
    --cov=sportorg
    --cov=user_registration
    --cov=frontend
    --cov-report=term-missing:skip-covered
    --cov-fail-under=65
