"""Слой хранения: только PostgreSQL (см. storage_postgres)."""

from user_registration.storage_postgres import (
    add_athlete_skill,
    add_team_member,
    apply_to_team,
    create_new_user,
    create_team,
    ensure_sport,
    finalize_team_roster,
    get_all_users,
    get_coach_team_detail,
    get_db_connection,
    get_user_by_email,
    get_user_by_id,
    init_db,
    list_available_teams,
    list_athlete_skills,
    list_coach_teams,
    list_my_team_applications,
    remove_team_member,
    replace_athlete_skills,
    save_team_members,
    search_sportsmen,
)

__all__ = (
    "add_athlete_skill",
    "add_team_member",
    "apply_to_team",
    "create_new_user",
    "create_team",
    "ensure_sport",
    "finalize_team_roster",
    "get_all_users",
    "get_coach_team_detail",
    "get_db_connection",
    "get_user_by_email",
    "get_user_by_id",
    "init_db",
    "list_available_teams",
    "list_athlete_skills",
    "list_coach_teams",
    "list_my_team_applications",
    "remove_team_member",
    "replace_athlete_skills",
    "save_team_members",
    "search_sportsmen",
)
